CREATE_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS telegram_users (
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
USERNAME CHAR(50),
FIRST_NAME CHAR(50),
LAST_NAME CHAR(50),
UNIQUE (TELEGRAM_ID)
)"""


INSERT_USER_QUERY = """
INSERT INTO telegram_users VALUES (?, ?, ?, ?, ?)
"""

CREATE_BAN_USER_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS ban_users (
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
BAN_COUNT INTEGER,
UNIQUE (TELEGRAM_ID)
)"""


INSERT_BAN_USER_QUERY = """
INSERT INTO ban_users VALUES (?, ?, ?)
"""

SELECT_BAN_USER_QUERY = """
SELECT * FROM ban_users WHERE TELEGRAM_ID = ?
"""

UPDATE_BAN_USER_TABLE_QUERY = """
UPDATE ban_users SET BAN_COUNT = BAN_COUNT + 1 WHERE TELEGRAM_ID = ?
"""


CREATE_PROFILE_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS profile (
ID INTEGER PRIMARY KEY,
TELEGRAM_ID INTEGER,
NICKNAME CHAR(50),
BIO TEXT,
AGE INTEGER,
GENDER CHAR(50),
HOBBY CHAR(50),
ZODIAC_SIGN CHAR(50),
PHOTO TEXT,
UNIQUE (TELEGRAM_ID)
)"""

INSERT_PROFILE_USER_QUERY = """
INSERT INTO profile VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
"""

SELECT_PROFILE_USER_QUERY = """
SELECT TELEGRAM_ID FROM profile WHERE TELEGRAM_ID = ?"""